### ISSUE TITLE
Does this Work with Angular 12

### ISSUE THREAD

**Issue by mtayyabmakki** [AhamedBilal/ngx-photo-editor#22]
**these are my dependencies in package.json**
"@angular/animations": "12.1.1",
"@angular/cdk": "12.1.1",
"@angular/common": "12.1.1",
"@angular/compiler": "12.1.1",
"@angular/core": "12.1.1",
"@angular/forms": "12.1.1",
"@angular/google-maps": "^12.1.1",
"@angular/material": "12.1.1",
"@angular/platform-browser": "12.1.1",
"@angular/platform-browser-dynamic": "12.1.1",
"tslib": "2.3.0",
**Getting This ERROR**
 Generating browser application bundles (phase: setup)...E:\Angular Projects\linksupercharger-loopback-server\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
                ^

Error: The target entry-point "ngx-photo-editor" has missing dependencies:
 - @ng-bootstrap/ng-bootstrap

    at TargetedEntryPointFinder.findEntryPoints (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (E:\Angular Projects\project\ng-admin\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (E:\Angular Projects\project\ng-admin\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at E:\Angular Projects\project\ng-admin\node_modules\@ngtools\webpack\src\ivy\host.js:146:18
    at E:\Angular Projects\project\ng-admin\node_modules\@ngtools\webpack\src\ivy\host.js:76:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (E:\Angular Projects\project\ng-admin\node_modules\@ngtools\webpack\src\ivy\host.js:74:32)
    at actualResolveModuleNamesWorker (E:\Angular Projects\project\ng-admin\node_modules\typescript\lib\typescript.js:109497:133)
    at resolveModuleNamesWorker (E:\Angular Projects\project\ng-admin\node_modules\typescript\lib\typescript.js:109760:26)
    at resolveModuleNamesReusingOldState (E:\Angular Projects\project\ng-admin\node_modules\typescript\lib\typescript.js:109857:24)

**Comment by mtayyabmakki** [comment]
is this library compatible with Angular Ivy

**Comment by AhamedBilal** [comment]
I'm currently working on the new version with angular 14 support. Will be available tomorrow

**Comment by AhamedBilal** [comment]
package  updated. now it will work on all the new versions

**Comment by mtayyabmakki** [comment]
Awesome, thanks!

**Comment by mtayyabmakki** [comment]
Will this work with angular version 12?
